# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Pro Max",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
